# Generated by Django 5.0.4 on 2024-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='genre',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='writer',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
