# Generated by Django 5.0.1 on 2024-05-08 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='writer',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
