# Generated by Django 5.0.4 on 2024-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusback', '0002_draft_genre_draft_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='drawSty',
        ),
        migrations.AlterField(
            model_name='draft',
            name='genre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='writer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='intro',
            name='IntroContent',
            field=models.TextField(null=True),
        ),
    ]
