# Generated by Django 5.0.1 on 2024-05-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusback', '0003_remove_draft_drawsty_alter_draft_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='copyR',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='achieveCnt',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='flowerImg',
        ),
        migrations.RemoveField(
            model_name='myforest',
            name='flower',
        ),
        migrations.AddField(
            model_name='draftpage',
            name='pageImage',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
